version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 5433:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=AdminACI321
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"