{{- $replicaCount := .Values.replicaCount -}}
{{- range $index, $microservice := .Values.microservices}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aci-{{ $microservice.name }}
spec:
  selector:
    matchLabels:
      app: aci-{{ $microservice.name }}
  replicas: {{ $replicaCount }}
  template:
    metadata:
      labels:
        app: aci-{{ $microservice.name }}
    spec:
      containers:
      - name: aci-{{ $microservice.name }}
        image: {{ $microservice.image }}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets
          mountPath: app/appsettings.json
          subPath: appsettings.json
      volumes:
      - name: secrets
        secret:
          secretName: {{ $microservice.name }}-appsettings
          optional: false 
# --- etc ---
{{- end }}