{{- $files := .Files }}
{{- range $index, $microservice := .Values.microservices}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $microservice.name }}-appsettings
data:
  appsettings.json: |-
{{ printf "secrets/%s/appsettings.json" $microservice.name | $files.Get | b64enc | indent 6 }}
{{- end }}