name: Build the ProductService

on:
  push:
    branches:
      - main
    paths:
      - "ACI.Products/**"
      - "ACI.Products.Test/**"
      - ".github/workflows/build-product-service.yml"
  pull_request:
    branches:
      - main
      - dev
      - S6_S2022_dev
    paths:
      - "ACI.Products/**"
      - "ACI.Products.Test/**"
      - ".github/workflows/build-product-service.yml"

env:
  PROJECT_PATH: 'ACI.Products/ACI.Products.csproj'
  TEST_PATH: 'ACI.Products.Test/ACI.Products.Test.csproj'
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_PRODUCT_SERVICE }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

    - name: Run tests
      run: dotnet test ${{ env.TEST_PATH }}

    # https://github.com/highbyte/sonarscan-dotnet
    - name: SonarScanner for .NET 5
      uses: highbyte/sonarscan-dotnet@2.0
      with:
        sonarProjectKey: aci-rental_backend-product-service
        sonarProjectName:  backend-product-service
        sonarOrganization: aci-rental
        dotnetBuildArguments: ./ACI.Products
        dotnetTestArguments: ./ACI.Products.Tests
