name: Build the UserService

on:
  push:
    branches:
      - main
    paths:
      - "UserService/**"
      - "UserService.Tests/**"
      - ".github/workflows/build-user-service.yml"
  pull_request:
    branches: 
      - main
      - dev
    paths:
      - "UserService/**"
      - "UserService.Tests/**"
      - ".github/workflows/build-user-service.yml"

env:
  PROJECT_PATH: 'UserService/UserService.csproj'
  TEST_PATH: 'UserService.Tests/UserService.Tests.csproj'
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_USER_SERVICE }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

    - name: Run tests
      run: dotnet test ${{ env.TEST_PATH }}

      # https://github.com/highbyte/sonarscan-dotnet
    - name: SonarScanner for .NET 5
      uses: highbyte/sonarscan-dotnet@2.0
      with:
        sonarProjectKey: aci-rental_backend-user-service
        sonarProjectName:  backend-user-service
        sonarOrganization: aci-rental
        dotnetBuildArguments: ./UserService
        dotnetTestArguments: ./UserService.Tests
