name: Build/Test/Analyze ACI.Products

on:
  push:
    branches:
      - main
    paths:
      - "ACI.Products/**"
      - "ACI.Products.Test.*/**"
      - ".github/workflows/build-product-service.yml"
  pull_request:
    branches:
      - main
      - dev
      - S6_S2022_dev
    paths:
      - "ACI.Products/**"
      - "ACI.Products.Test.*/**"
      - ".github/workflows/build-product-service.yml"

env:
  PROJECT_PATH: 'ACI.Products/ACI.Products.csproj'
  UNIT_TEST_PATH: 'ACI.Products.Test.Unit/ACI.Products.Test.Unit.csproj'
  INTEGRATION_TEST_PATH: 'ACI.Products.Test.Integration/ACI.Products.Test.Integration.csproj'
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_PRODUCT_SERVICE }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Compile and run code style checks'
      run: dotnet build ${{ env.PROJECT_PATH }} /p:TreatWarningsAsErrors=true --no-restore --configuration Release -clp:NoSummary

  test:
    needs: build-and-lint
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3.9-management
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672
          - 15672:15672

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: 'Install Sonar global tool'
      run: dotnet tool install --global dotnet-sonarscanner

    - name: 'Begin Sonar scan'
      run: >
        dotnet sonarscanner begin
        /d:sonar.host.url="https://sonarcloud.io"
        /o:"aci-rental"
        /k:"aci.microservice.product"
        /d:sonar.login=${{ env.SONAR_TOKEN }}
        /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
        /d:sonar.sources="ACI.Products/**"
        /d:sonar.exclusions="ACI.Products.Test.*/**"
        /d:sonar.test.exclusions="ACI.Products.Test.*/**"

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release -clp:NoSummary

    - name: 'Run unit tests'
      run: dotnet test ${{ env.UNIT_TEST_PATH }} /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --verbosity normal

    - name: 'Run integration tests'
      run: dotnet test ${{ env.INTEGRATION_TEST_PATH }} /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --verbosity normal

    - name: 'End Sonar scan'
      run: dotnet sonarscanner end /d:sonar.login=${{ env.SONAR_TOKEN }}

