name: Build the OcelotAPIGateway

on:
  push:
    branches:
      - main
    paths:
      - "OcelotAPIGateway/**"
      - ".github/workflows/build-api-gateway.yml"
  pull_request:
    branches: 
      - main
      - dev
      - S6_S2022_dev
    paths:
      - "OcelotAPIGateway/**"
      - ".github/workflows/build-api-gateway.yml"

env:
  PROJECT_PATH: 'OcelotAPIGateway/OcelotAPIGateway.csproj'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release