name: Build ACI.Gateway

on:
  push:
    branches:
      - main
    paths:
      - "ACI.Gateway/**"
      - ".github/workflows/build-api-gateway.yml"
  pull_request:
    branches:
      - main
      - dev
      - S6_S2022_dev
    paths:
      - "ACI.Gateway/**"
      - ".github/workflows/build-api-gateway.yml"

env:
  PROJECT_PATH: 'ACI.Gateway/ACI.Gateway.csproj'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Install dotnet'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: 'Restore packages'
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: 'Compile and run code style checks'
        run: dotnet build ${{ env.PROJECT_PATH }} /p:TreatWarningsAsErrors=true --no-restore --configuration Release -clp:NoSummary