name: Build the ProductService

on:
  push:
    branches:
      - main
    paths:
      - "ACI.Products/**"
      - "ACI.Products.Test.*/**"
      - ".github/workflows/build-product-service.yml"
  pull_request:
    branches:
      - main
      - dev
      - S6_S2022_dev
    paths:
      - "ACI.Products/**"
      - "ACI.Products.Test.*/**"
      - ".github/workflows/build-product-service.yml"

env:
  PROJECT_PATH: 'ACI.Products/ACI.Products.csproj'
  UNIT_TEST_PATH: 'ACI.Products.Test/ACI.Products.Test.Unit.csproj'
  INTEGRATION_TEST_PATH: 'ACI.Products.Test/ACI.Products.Test.Integration.csproj'
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_PRODUCT_SERVICE }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} /p:TreatWarningsAsErrors=true --no-restore --configuration Release

    - name: 'Run unit tests'
      run: dotnet test ${{ env.UNIT_TEST_PATH }} --no-build --verbosity normal

    - name: 'Run integration tests'
      run: dotnet test ${{ env.INTEGRATION_TEST_PATH }} --no-build --verbosity normal

    # https://github.com/highbyte/sonarscan-dotnet
    - name: SonarScanner for .NET 6 with pull request decoration support
      uses: highbyte/sonarscan-dotnet@v2.1.2
      with:
        sonarProjectKey: aci-product-service
        sonarProjectName:  aci-rental
        sonarOrganization: aci-rental
        dotnetBuildArguments: ./ACI.Products
        dotnetTestArguments: ./ACI.Products.Tests
